version: '3'

volumes:
  static_volume:
  media_volume:
  pg_data_production:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: vasiliykovalev17/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
    depends_on:
      - db
  frontend:
    image: vasiliykovalev17/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: vasiliykovalev17/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - backend
